{
 "title": "IOTA Mainnet Validators",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Network Epoch",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, current_epoch{network=\"mainnet\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Validators Not in Current Epoch",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_epoch{network=\"mainnet\"} < scalar(quantile(0.67, current_epoch{network=\"mainnet\"}))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Safe Mode",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_system_state_safe_mode{network=\"mainnet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Protocol Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "iota_system_state_protocol_version{network=\"mainnet\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest Checkpoint",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(last_executed_checkpoint{network=\"mainnet\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Network overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Voting power distribution",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "current_voting_right{network=\"mainnet\"} / 10000",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Certificates handled by validators",
   "type": "timeseries",
   "description": "Cert per sec (median across validators)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "quantile(0.5, sum by (host) (rate(total_transaction_certificates{network=\"mainnet\"}[5m])) - sum by (host) (rate(num_shared_obj_tx{network=\"mainnet\"}[5m])))",
     "legendFormat": "owned obj txns"
    },
    {
     "expr": "quantile(0.5, rate(num_shared_obj_tx{network=\"mainnet\"}[5m]))",
     "legendFormat": "shared obj txns"
    }
   ]
  },
  {
   "title": "Cert processing latencies on validators",
   "type": "timeseries",
   "description": "p50 and p95 percentiles per validator, p67 across validators",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile(0.67, validator_service_handle_certificate_consensus_latency{network=\"mainnet\", pct=\"50\"})",
     "legendFormat": "shared-obj-p50"
    },
    {
     "expr": "quantile(0.67, validator_service_handle_certificate_non_consensus_latency{network=\"mainnet\", pct=\"50\"})",
     "legendFormat": "owned-obj-p50"
    },
    {
     "expr": "quantile(0.67, validator_service_handle_certificate_consensus_latency{network=\"mainnet\", pct=\"95\"})",
     "legendFormat": "shared-obj-p95"
    },
    {
     "expr": "quantile(0.67, validator_service_handle_certificate_non_consensus_latency{network=\"mainnet\", pct=\"95\"})",
     "legendFormat": "owned-obj-p95"
    }
   ]
  },
  {
   "title": "Validator versions",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(host, version) (uptime{network=\"mainnet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of stake that increments checkpoints",
   "type": "timeseries",
   "description": "The overall part of the stake that increments the checkpoints",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum(current_voting_right{network=\"mainnet\"} and rate(last_executed_checkpoint{network=\"mainnet\"}[5m]) > 0) / 10000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pct of stake w/ p95 shared obj latency < 7 seconds",
   "type": "timeseries",
   "description": "Pct of stake across all the validators that report p95 shared obj latencies below 7 seconds",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (\nsum by (host) (current_voting_right{network=\"mainnet\"})\nand\nsum by (host) (avg_over_time(validator_service_handle_certificate_consensus_latency{network=\"mainnet\", pct=\"95\"}[5m:1m])) / 1000 < 7.0\n) / 10000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of stake that increments consensus rounds",
   "type": "timeseries",
   "description": "The overall part of the stake that increments the rounds",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(current_voting_right{network=\"mainnet\"} and rate(current_round{network=\"mainnet\"}[5m]) > 0) / 10000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Avg Consensus Adapter e2e latency",
   "type": "timeseries",
   "description": "e2e latency of handling certificates that go through Narwhal (p67 across validators)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.67, (sum by (host) (sequencing_certificate_latency_sum{network=\"mainnet\"}) / sum by (host) (sequencing_certificate_latency_count{network=\"mainnet\"}))) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Validator performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Cert processing latency: p95 shared objects",
   "type": "status-history",
   "description": "Shared obj p95 cert processing latency is supposed to be below 10 sec",
   "gridPos": { "h": 29, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "avg_over_time(validator_service_handle_certificate_consensus_latency{network=\"mainnet\", pct=\"95\"}[5m:1m]) / 1000",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Average time to generate consensus proposal latency",
   "type": "status-history",
   "gridPos": { "h": 29, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "sum by(host) (rate(proposer_batch_latency_sum{network=\"mainnet\"}[5m]))\n/\nsum by(host) (rate(proposer_batch_latency_count{network=\"mainnet\"}[5m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "p50 process certificate (internal processing only)",
   "type": "status-history",
   "gridPos": { "h": 29, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, host) (rate(primary_inbound_request_latency_bucket{network=\"mainnet\", route=\"/narwhal.PrimaryToPrimary/SendCertificate\"}[5m]))) * 1000",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Fullnode Connectivity",
   "type": "status-history",
   "description": "Error rate (as reported by all the IOTA Foundation FNs) for the RPC errors",
   "gridPos": { "h": 29, "w": 8, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by (name) (rate(total_rpc_err{network=\"mainnet\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Consensus network connectivity",
   "type": "status-history",
   "description": "Number of connected primary peers per validator",
   "gridPos": { "h": 29, "w": 8, "x": 8, "y": 65 },
   "targets": [
    {
     "expr": " sum by(host) (primary_network_peer_connected{network=\"mainnet\", type=\"other_primary\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus proposal rate",
   "type": "status-history",
   "description": "The rate of node participation in consensus via sending certified Narwhal proposals.",
   "gridPos": { "h": 29, "w": 8, "x": 16, "y": 65 },
   "targets": [
    {
     "expr": "sum by (host) (rate(certificates_created{network=\"mainnet\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last commit round lag",
   "type": "status-history",
   "description": "Shows the lag (diff) between the median reported last committed round and the specific host's last committed round. The color scheme shows how far behind nodes are.",
   "gridPos": { "h": 29, "w": 8, "x": 16, "y": 94 },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "$B - $A",
     "reducer": "max",
     "type": "math"
    }
   ]
  }
 ]
}